# Generated by Django 2.2.4 on 2021-04-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='immunization',
            name='renew_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='start_date',
            field=models.DateField(),
        ),
    ]
